[package]
name = "market-integration-tests"
version.workspace = true
edition.workspace = true

[dependencies]
near-workspaces = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
anyhow = "1"
